apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-pulse-staging

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: devops-pulse-backend
      spec:
        replicas: 2

  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: devops-pulse
      spec:
        rules:
          - host: devops-pulse-staging.local
