apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-pulse
  labels:
    app: devops-pulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: devops-pulse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-pulse-backend
                port:
                  number: 80
